#!/bin/bash

set -e

#DEBHELPER#

case "$1" in
    configure)
	if [ -x /usr/sbin/update-bash-completion ]; then
		update-bash-completion
	fi
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
